"""
Single LLM client for the whole pipeline.

Provider and model per role come from config/llm.yaml: gemini (default), openai_compatible (e.g. a vLLM
server: base_url + model; tool calling via the OpenAI tools API; /v1/embeddings), local (in-process
sentence-transformers embeddings). Every response is
cached as one JSON file under data/cache/llm/, keyed by (provider, model, thinking, system, prompt,
schema, seed), so reruns are free and reproducible, and a single bad output can be regenerated by
changing its seed.

No silent fallbacks: any failed request raises LLMError. Every result records `served_model`, the
model the provider reports actually answered, in both the cache entry and the returned metadata.
"""
import hashlib
import json
import os
import re
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent


def load_dotenv(path=ROOT / ".env"):
    """Load KEY=value lines from the git-ignored .env; real environment variables win."""
    if path.exists():
        for line in path.read_text().splitlines():
            key, sep, value = line.partition("=")
            if sep and key.strip() and not key.lstrip().startswith("#"):
                os.environ.setdefault(key.strip(), value.strip())


load_dotenv()


class LLMError(RuntimeError):
    pass


class BadOutputError(LLMError):
    """The request succeeded but the output is unusable (a bad output, not an API failure)."""


class EmptyResponseError(BadOutputError):
    """The model returned no content."""


class TruncatedResponseError(BadOutputError):
    """The model hit max_tokens."""


class BlockedResponseError(BadOutputError):
    """The provider's safety filter blocked the output (SAFETY, PROHIBITED_CONTENT, ...)."""


BLOCKED_REASONS = {"SAFETY", "PROHIBITED_CONTENT", "BLOCKLIST", "SPII", "RECITATION", "IMAGE_SAFETY"}


@dataclass
class LLMResult:
    output: dict        # validated against the schema
    meta: dict          # provider, model, served_model, thinking, seed, cache_key — copy into output records


@dataclass
class ChatResult:
    content: dict       # provider-native assistant message, appended as-is to the next request
    meta: dict

    @property
    def calls(self):
        """[(name, args, id)] for every function call in the message."""
        if "parts" not in self.content:                              # OpenAI-style message
            return [(c["function"]["name"], parse_args(c["function"].get("arguments")), c.get("id"))
                    for c in self.content.get("tool_calls") or []]
        return [(p["function_call"]["name"], p["function_call"].get("args") or {}, p["function_call"].get("id"))
                for p in self.content.get("parts", []) if p.get("function_call")]

    @property
    def text(self):
        if "parts" not in self.content:
            return (self.content.get("content") or "").strip()
        return "".join(p.get("text", "") for p in self.content.get("parts", [])
                       if p.get("text") and not p.get("thought")).strip()


def parse_args(arguments):
    """OpenAI tool-call arguments arrive as a JSON string; an unparsable string is a bad output."""
    if isinstance(arguments, dict):
        return arguments
    try:
        return json.loads(arguments or "{}")
    except json.JSONDecodeError as e:
        raise BadOutputError(f"tool call arguments are not valid JSON: {arguments!r}") from e


class LLM:
    def __init__(self, role="generation", config_path=ROOT / "config" / "llm.yaml"):
        cfg = yaml.safe_load(Path(config_path).read_text())
        spec = cfg["roles"][role]
        if not spec.get("provider") or not spec.get("model"):
            raise LLMError(f"no provider/model configured for role {role!r} in {config_path}")
        providers = set(BACKENDS) | set(CHATTERS) | set(EMBEDDERS)
        if spec["provider"] not in providers:
            raise LLMError(f"unsupported provider {spec['provider']!r}; choose from {sorted(providers)}")
        self.spec = spec                        # provider-specific keys: base_url, api_key_env, extra_body, ...
        self.role = role
        self.provider = spec["provider"]
        self.model = spec["model"]
        self.thinking = spec.get("thinking", "high")
        self.max_tokens = spec.get("max_tokens", 16000)
        self.dimensions = spec.get("dimensions")
        self.cache_dir = ROOT / cfg["cache_dir"]
        self._client = None
        self._lock = threading.Lock()          # one shared client, created once, across threads

    # ------------------------------------------------------------------ public
    def json(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> LLMResult:
        """Structured output validated against `schema`, plus generation metadata."""
        path = self._cache_path(prompt, schema, seed, system)
        if path.exists():
            entry = json.loads(path.read_text())
        else:
            output, served_model = BACKENDS[self.provider](self, system, prompt, schema, seed)
            entry = {
                "provider": self.provider, "model": self.model, "served_model": served_model,
                "thinking": self.thinking, "seed": seed, "system": system, "prompt": prompt,
                "schema": schema.__name__, "output": output,
            }
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(entry, indent=2, ensure_ascii=False))
        schema.model_validate(entry["output"])
        meta = {k: entry[k] for k in ("provider", "model", "served_model", "thinking", "seed")}
        return LLMResult(entry["output"], {**meta, "cache_key": path.stem})

    def embed(self, texts: list) -> np.ndarray:
        """Unit-normalized embeddings, one row per text. Cached per (model, dimensions, text)."""
        path = self.cache_dir / f"embeddings_{self.provider}_{self.model}_{self.dimensions}.npz"
        cache = dict(np.load(path)) if path.exists() else {}
        keys = [hashlib.sha256(t.encode()).hexdigest()[:24] for t in texts]
        missing = sorted({(k, t) for k, t in zip(keys, texts) if k not in cache})
        if missing:
            if self.provider not in EMBEDDERS:
                raise LLMError(f"provider {self.provider!r} has no embedding backend")
            vecs = EMBEDDERS[self.provider](self, [t for _, t in missing])
            if len(vecs) != len(missing):
                raise LLMError(f"asked for {len(missing)} embeddings, got {len(vecs)}")
            cache.update({k: v for (k, _), v in zip(missing, vecs)})
            path.parent.mkdir(parents=True, exist_ok=True)
            np.savez(path, **cache)
        v = np.array([cache[k] for k in keys], dtype=np.float32)
        return v / np.linalg.norm(v, axis=1, keepdims=True)

    def chat(self, system: str, contents: list, tools: list, seed) -> "ChatResult":
        """One function-calling turn. `contents` are provider-native message dicts (JSON-safe); `tools` are
        neutral declarations {name, description, parameters (JSON schema)}. Cached like json()."""
        blob = json.dumps([self.provider, self.model, self.thinking, system, contents, tools, str(seed)],
                          sort_keys=True, ensure_ascii=False)
        path = self.cache_dir / "chat" / f"{hashlib.sha256(blob.encode()).hexdigest()[:24]}.json"
        if path.exists():
            entry = json.loads(path.read_text())
        else:
            if self.provider not in CHATTERS:
                raise LLMError(f"provider {self.provider!r} has no chat backend")
            content, served_model = CHATTERS[self.provider](self, system, contents, tools, seed)
            entry = {"provider": self.provider, "model": self.model, "served_model": served_model,
                     "thinking": self.thinking, "seed": seed, "content": content}
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(entry, indent=2, ensure_ascii=False))
        meta = {k: entry[k] for k in ("provider", "model", "served_model", "thinking", "seed")}
        return ChatResult(entry["content"], {**meta, "cache_key": path.stem})

    # provider-native messages for the conversation the caller keeps (Gemini's shape is unchanged, so its
    # cached calls still hit)
    def user_message(self, text: str) -> dict:
        if self.provider == "openai_compatible":
            return {"role": "user", "content": text}
        return {"role": "user", "parts": [{"text": text}]}

    def tool_results(self, results) -> list:
        """results: [(name, call_id, result_dict)] -> messages to append after the assistant's tool calls."""
        if self.provider == "openai_compatible":
            return [{"role": "tool", "tool_call_id": cid, "name": name, "content": json.dumps(r, ensure_ascii=False)}
                    for name, cid, r in results]
        parts = []
        for name, cid, r in results:
            fr = {"name": name, "response": r}
            if cid:
                fr["id"] = cid
            parts.append({"function_response": fr})
        return [{"role": "user", "parts": parts}]

    def cached(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> bool:
        return self._cache_path(prompt, schema, seed, system).exists()

    # ------------------------------------------------------------------ internals
    def _cache_path(self, prompt, schema, seed, system):
        schema_json = json.dumps(schema.model_json_schema(), sort_keys=True)
        blob = json.dumps([self.provider, self.model, self.thinking, system, prompt, schema_json, str(seed)])
        return self.cache_dir / f"{hashlib.sha256(blob.encode()).hexdigest()[:24]}.json"


DEFAULT_TIMEOUT = 180       # seconds per request; a hung request fails and is retried instead of blocking forever


def gemini_client(llm):
    from google import genai
    from google.genai import types

    timeout = llm.spec.get("timeout", DEFAULT_TIMEOUT)
    return genai.Client(http_options=types.HttpOptions(timeout=int(timeout * 1000)))   # milliseconds


def int_seed(seed):
    """Stable 31-bit integer from any seed value (for providers that accept a sampling seed)."""
    return int(hashlib.sha256(str(seed).encode()).hexdigest(), 16) % (2 ** 31)


RETRY_CODES = {429, 503}          # rate limit / overloaded: same request, same model, after a wait
MAX_RETRIES = 5


def with_retries(fn, error_cls, what):
    """Retry only rate-limit/overload errors and dropped connections, loudly; anything else (or too many
    retries) raises LLMError."""
    import httpx

    transient = (httpx.RemoteProtocolError, httpx.ConnectError, httpx.TimeoutException)   # incl. request timeouts
    try:
        import openai
        transient += (openai.APIConnectionError,)          # includes APITimeoutError
    except ImportError:
        pass
    for attempt in range(MAX_RETRIES + 1):
        try:
            return fn()
        except transient as e:                                 # transient network drop
            if attempt == MAX_RETRIES:
                raise LLMError(f"{what} failed: {type(e).__name__}: {e}") from e
            print(f"[llm] {what}: {type(e).__name__}, retry {attempt + 1}/{MAX_RETRIES} in 10s", file=sys.stderr, flush=True)
            time.sleep(10)
        except error_cls as e:
            code = getattr(e, "status_code", None) or getattr(e, "code", None)   # openai / genai
            daily = "per_day" in str(e).lower() or "perday" in str(e).lower()   # waiting won't help
            if code not in RETRY_CODES or daily or attempt == MAX_RETRIES:
                raise LLMError(f"{what} failed ({code}): {getattr(e, 'message', e)}") from e
            m = re.search(r"retry in ([\d.]+)s", str(e))
            wait = float(m.group(1)) + 1 if m else 30 * (attempt + 1)
            print(f"[llm] {what}: {code}, retry {attempt + 1}/{MAX_RETRIES} in {wait:.0f}s", file=sys.stderr, flush=True)
            time.sleep(wait)


# ---------------------------------------------------------------------- backends
def call_gemini(llm, system, prompt, schema, seed):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    with llm._lock:
        if llm._client is None:
            llm._client = gemini_client(llm)
    config = types.GenerateContentConfig(
        system_instruction=system or None,
        response_mime_type="application/json",
        response_schema=schema,
        max_output_tokens=llm.max_tokens,
        seed=int_seed(seed),
        thinking_config=types.ThinkingConfig(thinking_level=llm.thinking.upper()),
        automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
    )
    resp = with_retries(lambda: llm._client.models.generate_content(model=llm.model, contents=prompt, config=config),
                        genai.errors.APIError, "Gemini request")
    cand = resp.candidates[0] if resp.candidates else None
    reason = cand.finish_reason.name if cand and cand.finish_reason else None
    if reason == "MAX_TOKENS":
        raise TruncatedResponseError(f"output truncated at max_tokens={llm.max_tokens}")
    if reason in BLOCKED_REASONS:
        raise BlockedResponseError(f"Gemini blocked: finish_reason={reason}")
    if reason not in (None, "STOP"):
        raise LLMError(f"Gemini stopped with finish_reason={reason}")
    if resp.parsed is None:
        raise LLMError(f"no parsed output (finish_reason={reason}, feedback={resp.prompt_feedback})")
    if not resp.model_version:
        raise LLMError("Gemini response did not report which model answered")
    return resp.parsed.model_dump(), resp.model_version


def embed_gemini(llm, texts, batch=100):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    with llm._lock:
        if llm._client is None:
            llm._client = gemini_client(llm)
    config = types.EmbedContentConfig(output_dimensionality=llm.dimensions) if llm.dimensions else None
    out = []
    for i in range(0, len(texts), batch):
        chunk = texts[i:i + batch]
        # one Content per text; a bare list of strings is embedded as a single item
        contents = [types.Content(parts=[types.Part(text=t)]) for t in chunk]
        resp = with_retries(lambda: llm._client.models.embed_content(model=llm.model, contents=contents, config=config),
                            genai.errors.APIError, "Gemini embedding")
        if len(resp.embeddings) != len(chunk):
            raise LLMError(f"asked for {len(chunk)} embeddings, got {len(resp.embeddings)}")
        out += [np.array(e.values, dtype=np.float32) for e in resp.embeddings]
    return out


def chat_gemini(llm, system, contents, tools, seed):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    with llm._lock:
        if llm._client is None:
            llm._client = gemini_client(llm)
    decls = [types.FunctionDeclaration(name=t["name"], description=t["description"],
                                       parameters_json_schema=t["parameters"]) for t in tools]
    config = types.GenerateContentConfig(
        system_instruction=system or None,
        tools=[types.Tool(function_declarations=decls)] if decls else None,
        max_output_tokens=llm.max_tokens,
        seed=int_seed(seed),
        thinking_config=types.ThinkingConfig(thinking_level=llm.thinking.upper()),
        automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
    )
    msgs = [types.Content.model_validate(c) for c in contents]
    resp = with_retries(lambda: llm._client.models.generate_content(model=llm.model, contents=msgs, config=config),
                        genai.errors.APIError, "Gemini chat")
    cand = resp.candidates[0] if resp.candidates else None
    reason = cand.finish_reason.name if cand and cand.finish_reason else None
    if reason == "MAX_TOKENS":
        raise TruncatedResponseError(f"Gemini chat hit max_tokens={llm.max_tokens}")
    if reason in BLOCKED_REASONS:
        raise BlockedResponseError(f"Gemini chat blocked: finish_reason={reason}")
    if reason not in (None, "STOP"):
        raise LLMError(f"Gemini chat stopped with finish_reason={reason}")
    if not cand or not cand.content or not cand.content.parts:
        raise EmptyResponseError("Gemini chat returned an empty message")
    if not resp.model_version:
        raise LLMError("Gemini response did not report which model answered")
    return cand.content.model_dump(mode="json", exclude_none=True), resp.model_version


# ---------------------------------------------------------------------- OpenAI-compatible (vLLM)
def openai_client(llm):
    import openai

    with llm._lock:
        if llm._client is None:
            base_url = llm.spec.get("base_url")
            if not base_url:
                raise LLMError(f"openai_compatible role needs base_url (model {llm.model!r})")
            key = os.environ.get(llm.spec.get("api_key_env") or "", "") or "EMPTY"   # vLLM ignores it without --api-key
            llm._client = openai.OpenAI(base_url=base_url, api_key=key,
                                        timeout=llm.spec.get("timeout", DEFAULT_TIMEOUT), max_retries=0)
    return llm._client, openai


def openai_kwargs(llm, seed):
    kw = {"model": llm.model, "max_tokens": llm.max_tokens, "seed": int_seed(seed)}
    if llm.spec.get("temperature") is not None:
        kw["temperature"] = llm.spec["temperature"]
    if llm.spec.get("reasoning_effort"):
        kw["reasoning_effort"] = llm.spec["reasoning_effort"]
    if llm.spec.get("extra_body"):
        kw["extra_body"] = llm.spec["extra_body"]       # e.g. {chat_template_kwargs: {enable_thinking: false}}
    return kw


def check_openai_finish(choice, llm, what):
    reason = choice.finish_reason
    if reason == "length":
        raise TruncatedResponseError(f"{what} hit max_tokens={llm.max_tokens}")
    if reason == "content_filter":
        raise BlockedResponseError(f"{what} blocked: finish_reason=content_filter")


def call_openai(llm, system, prompt, schema, seed):
    client, openai = openai_client(llm)
    msgs = ([{"role": "system", "content": system}] if system else []) + [{"role": "user", "content": prompt}]
    fmt = {"type": "json_schema", "json_schema": {"name": schema.__name__, "schema": schema.model_json_schema()}}
    resp = with_retries(lambda: client.chat.completions.create(messages=msgs, response_format=fmt,
                                                                **openai_kwargs(llm, seed)),
                        openai.APIStatusError, "OpenAI-compatible request")
    choice = resp.choices[0]
    check_openai_finish(choice, llm, "OpenAI-compatible request")
    text = (choice.message.content or "").strip()
    if not text:
        raise EmptyResponseError("OpenAI-compatible request returned no content")
    try:
        output = schema.model_validate_json(text).model_dump()
    except Exception as e:
        raise BadOutputError(f"output does not match {schema.__name__}: {text[:200]!r}") from e
    return output, resp.model


def chat_openai(llm, system, contents, tools, seed):
    client, openai = openai_client(llm)
    msgs = ([{"role": "system", "content": system}] if system else []) + list(contents)
    decl = [{"type": "function", "function": {"name": t["name"], "description": t["description"],
                                              "parameters": t["parameters"]}} for t in tools]
    kw = openai_kwargs(llm, seed)
    if decl:
        kw.update(tools=decl, tool_choice="auto")      # needs --enable-auto-tool-choice --tool-call-parser on vLLM
    resp = with_retries(lambda: client.chat.completions.create(messages=msgs, **kw),
                        openai.APIStatusError, "OpenAI-compatible chat")
    choice = resp.choices[0]
    check_openai_finish(choice, llm, "OpenAI-compatible chat")
    m = choice.message
    if not (m.content or "").strip() and not m.tool_calls:
        raise EmptyResponseError("OpenAI-compatible chat returned an empty message")
    content = {"role": "assistant", "content": m.content}
    if m.tool_calls:
        content["tool_calls"] = [{"id": c.id, "type": "function",
                                  "function": {"name": c.function.name, "arguments": c.function.arguments}}
                                 for c in m.tool_calls]
    ChatResult(content, {}).calls                      # fail now (BadOutputError) if arguments are not JSON
    return content, resp.model


def embed_openai(llm, texts, batch=64):
    client, openai = openai_client(llm)
    out = []
    for i in range(0, len(texts), batch):
        chunk = texts[i:i + batch]
        kw = {"model": llm.model, "input": chunk}
        if llm.dimensions:
            kw["dimensions"] = llm.dimensions             # only if the served model supports it (matryoshka)
        resp = with_retries(lambda: client.embeddings.create(**kw), openai.APIStatusError, "OpenAI-compatible embedding")
        out += [np.array(d.embedding, dtype=np.float32) for d in sorted(resp.data, key=lambda d: d.index)]
    return out


def embed_local(llm, texts):
    """In-process embeddings with sentence-transformers (optional dependency; pip install sentence-transformers)."""
    with llm._lock:
        if llm._client is None:
            try:
                from sentence_transformers import SentenceTransformer
            except ImportError as e:
                raise LLMError("provider 'local' needs sentence-transformers: pip install sentence-transformers") from e
            llm._client = SentenceTransformer(llm.model, device=llm.spec.get("device"))
    vecs = llm._client.encode(texts, batch_size=64, normalize_embeddings=True, show_progress_bar=False)
    return [np.asarray(v, dtype=np.float32) for v in vecs]


BACKENDS = {"gemini": call_gemini, "openai_compatible": call_openai}
EMBEDDERS = {"gemini": embed_gemini, "openai_compatible": embed_openai, "local": embed_local}
CHATTERS = {"gemini": chat_gemini, "openai_compatible": chat_openai}
