"""
Single LLM client for the whole pipeline.

Provider and model per role come from config/llm.yaml (gemini or anthropic). Every response is
cached as one JSON file under data/cache/llm/, keyed by (provider, model, thinking, system, prompt,
schema, seed), so reruns are free and reproducible, and a single bad output can be regenerated by
changing its seed.
"""
import hashlib
import json
import os
from pathlib import Path

import yaml
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent
ANTHROPIC_FALLBACK_BETA = "server-side-fallback-2026-07-01"


class LLMError(RuntimeError):
    pass


class LLM:
    def __init__(self, role="generation", config_path=ROOT / "config" / "llm.yaml"):
        cfg = yaml.safe_load(Path(config_path).read_text())
        spec = cfg["roles"][role]
        if not spec.get("provider") or not spec.get("model"):
            raise LLMError(f"no provider/model configured for role {role!r} in {config_path}")
        if spec["provider"] not in BACKENDS:
            raise LLMError(f"unsupported provider {spec['provider']!r}; choose from {sorted(BACKENDS)}")
        self.provider = spec["provider"]
        self.model = spec["model"]
        self.thinking = spec.get("thinking", "high")
        self.max_tokens = spec.get("max_tokens", 16000)
        self.provider_cfg = cfg.get(self.provider) or {}
        self.cache_dir = ROOT / cfg["cache_dir"]
        self._client = None

    # ------------------------------------------------------------------ public
    def json(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> dict:
        """Structured output validated against `schema`; returns a plain dict."""
        path = self._cache_path(prompt, schema, seed, system)
        if path.exists():
            return json.loads(path.read_text())["output"]

        output = BACKENDS[self.provider](self, system, prompt, schema, seed)
        schema.model_validate(output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({
            "provider": self.provider, "model": self.model, "thinking": self.thinking,
            "seed": seed, "system": system, "prompt": prompt, "schema": schema.__name__,
            "output": output,
        }, indent=2, ensure_ascii=False))
        return output

    def cached(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> bool:
        return self._cache_path(prompt, schema, seed, system).exists()

    # ------------------------------------------------------------------ internals
    def _cache_path(self, prompt, schema, seed, system):
        schema_json = json.dumps(schema.model_json_schema(), sort_keys=True)
        blob = json.dumps([self.provider, self.model, self.thinking, system, prompt, schema_json, str(seed)])
        return self.cache_dir / f"{hashlib.sha256(blob.encode()).hexdigest()[:24]}.json"


def int_seed(seed):
    """Stable 31-bit integer from any seed value (for providers that accept a sampling seed)."""
    return int(hashlib.sha256(str(seed).encode()).hexdigest(), 16) % (2 ** 31)


# ---------------------------------------------------------------------- backends
def call_gemini(llm, system, prompt, schema, seed):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    if llm._client is None:
        llm._client = genai.Client()
    config = types.GenerateContentConfig(
        system_instruction=system or None,
        response_mime_type="application/json",
        response_schema=schema,
        max_output_tokens=llm.max_tokens,
        seed=int_seed(seed),
        thinking_config=types.ThinkingConfig(thinking_level=llm.thinking.upper()),
    )
    try:
        resp = llm._client.models.generate_content(model=llm.model, contents=prompt, config=config)
    except genai.errors.ClientError as e:
        raise LLMError(f"Gemini request failed ({e.code}): {e.message}") from e
    cand = resp.candidates[0] if resp.candidates else None
    reason = cand.finish_reason.name if cand and cand.finish_reason else None
    if reason == "MAX_TOKENS":
        raise LLMError(f"output truncated at max_tokens={llm.max_tokens}")
    if resp.parsed is None:
        raise LLMError(f"no parsed output (finish_reason={reason}, feedback={resp.prompt_feedback})")
    return resp.parsed.model_dump()


def call_anthropic(llm, system, prompt, schema, seed):
    import anthropic

    if llm._client is None:
        llm._client = anthropic.Anthropic()
    kwargs = dict(
        model=llm.model,
        max_tokens=llm.max_tokens,
        messages=[{"role": "user", "content": prompt}],
        output_format=schema,
        output_config={"effort": llm.thinking},
    )
    if system:
        kwargs["system"] = system
    if llm.provider_cfg.get("fallbacks"):
        kwargs.update(betas=[ANTHROPIC_FALLBACK_BETA], fallbacks=llm.provider_cfg["fallbacks"])
    try:
        resp = llm._client.beta.messages.parse(**kwargs)
    except anthropic.AuthenticationError as e:
        raise LLMError("no valid Anthropic credentials: set ANTHROPIC_API_KEY") from e
    except TypeError as e:          # SDK raises this when no credential resolves at all
        if "api_key" in str(e) or "auth" in str(e).lower():
            raise LLMError("no Anthropic credentials: set ANTHROPIC_API_KEY") from e
        raise
    if resp.stop_reason == "refusal":
        raise LLMError(f"model refused (request {resp._request_id}): {resp.stop_details}")
    if resp.stop_reason == "max_tokens":
        raise LLMError(f"output truncated at max_tokens={llm.max_tokens}")
    if resp.parsed_output is None:
        raise LLMError(f"no parsed output (stop_reason={resp.stop_reason})")
    return resp.parsed_output.model_dump()


BACKENDS = {"gemini": call_gemini, "anthropic": call_anthropic}
