"""
Single LLM client for the whole pipeline.

Provider and model per role come from config/llm.yaml (gemini or anthropic). Every response is
cached as one JSON file under data/cache/llm/, keyed by (provider, model, thinking, system, prompt,
schema, seed), so reruns are free and reproducible, and a single bad output can be regenerated by
changing its seed.

No silent fallbacks: any failed request raises LLMError. Every result records `served_model`, the
model the provider reports actually answered, in both the cache entry and the returned metadata.
"""
import hashlib
import json
import os
import re
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent
ANTHROPIC_FALLBACK_BETA = "server-side-fallback-2026-07-01"


def load_dotenv(path=ROOT / ".env"):
    """Load KEY=value lines from the git-ignored .env; real environment variables win."""
    if path.exists():
        for line in path.read_text().splitlines():
            key, sep, value = line.partition("=")
            if sep and key.strip() and not key.lstrip().startswith("#"):
                os.environ.setdefault(key.strip(), value.strip())


load_dotenv()


class LLMError(RuntimeError):
    pass


@dataclass
class LLMResult:
    output: dict        # validated against the schema
    meta: dict          # provider, model, served_model, thinking, seed, cache_key — copy into output records


class LLM:
    def __init__(self, role="generation", config_path=ROOT / "config" / "llm.yaml"):
        cfg = yaml.safe_load(Path(config_path).read_text())
        spec = cfg["roles"][role]
        if not spec.get("provider") or not spec.get("model"):
            raise LLMError(f"no provider/model configured for role {role!r} in {config_path}")
        if spec["provider"] not in BACKENDS:
            raise LLMError(f"unsupported provider {spec['provider']!r}; choose from {sorted(BACKENDS)}")
        self.provider = spec["provider"]
        self.model = spec["model"]
        self.thinking = spec.get("thinking", "high")
        self.max_tokens = spec.get("max_tokens", 16000)
        self.dimensions = spec.get("dimensions")
        self.provider_cfg = cfg.get(self.provider) or {}
        self.cache_dir = ROOT / cfg["cache_dir"]
        self._client = None
        self._lock = threading.Lock()          # one shared client, created once, across threads

    # ------------------------------------------------------------------ public
    def json(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> LLMResult:
        """Structured output validated against `schema`, plus generation metadata."""
        path = self._cache_path(prompt, schema, seed, system)
        if path.exists():
            entry = json.loads(path.read_text())
        else:
            output, served_model = BACKENDS[self.provider](self, system, prompt, schema, seed)
            entry = {
                "provider": self.provider, "model": self.model, "served_model": served_model,
                "thinking": self.thinking, "seed": seed, "system": system, "prompt": prompt,
                "schema": schema.__name__, "output": output,
            }
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(entry, indent=2, ensure_ascii=False))
        schema.model_validate(entry["output"])
        meta = {k: entry[k] for k in ("provider", "model", "served_model", "thinking", "seed")}
        return LLMResult(entry["output"], {**meta, "cache_key": path.stem})

    def embed(self, texts: list) -> np.ndarray:
        """Unit-normalized embeddings, one row per text. Cached per (model, dimensions, text)."""
        path = self.cache_dir / f"embeddings_{self.provider}_{self.model}_{self.dimensions}.npz"
        cache = dict(np.load(path)) if path.exists() else {}
        keys = [hashlib.sha256(t.encode()).hexdigest()[:24] for t in texts]
        missing = sorted({(k, t) for k, t in zip(keys, texts) if k not in cache})
        if missing:
            if self.provider not in EMBEDDERS:
                raise LLMError(f"provider {self.provider!r} has no embedding backend")
            vecs = EMBEDDERS[self.provider](self, [t for _, t in missing])
            cache.update({k: v for (k, _), v in zip(missing, vecs)})
            path.parent.mkdir(parents=True, exist_ok=True)
            np.savez(path, **cache)
        v = np.array([cache[k] for k in keys], dtype=np.float32)
        return v / np.linalg.norm(v, axis=1, keepdims=True)

    def cached(self, prompt: str, schema: type[BaseModel], seed, system: str = "") -> bool:
        return self._cache_path(prompt, schema, seed, system).exists()

    # ------------------------------------------------------------------ internals
    def _cache_path(self, prompt, schema, seed, system):
        schema_json = json.dumps(schema.model_json_schema(), sort_keys=True)
        blob = json.dumps([self.provider, self.model, self.thinking, system, prompt, schema_json, str(seed)])
        return self.cache_dir / f"{hashlib.sha256(blob.encode()).hexdigest()[:24]}.json"


def int_seed(seed):
    """Stable 31-bit integer from any seed value (for providers that accept a sampling seed)."""
    return int(hashlib.sha256(str(seed).encode()).hexdigest(), 16) % (2 ** 31)


RETRY_CODES = {429, 503}          # rate limit / overloaded: same request, same model, after a wait
MAX_RETRIES = 5


def with_retries(fn, error_cls, what):
    """Retry only rate-limit/overload errors, loudly; anything else (or too many retries) raises LLMError."""
    for attempt in range(MAX_RETRIES + 1):
        try:
            return fn()
        except error_cls as e:
            code = getattr(e, "code", None)
            daily = "per_day" in str(e).lower() or "perday" in str(e).lower()   # waiting won't help
            if code not in RETRY_CODES or daily or attempt == MAX_RETRIES:
                raise LLMError(f"{what} failed ({code}): {getattr(e, 'message', e)}") from e
            m = re.search(r"retry in ([\d.]+)s", str(e))
            wait = float(m.group(1)) + 1 if m else 30 * (attempt + 1)
            print(f"[llm] {what}: {code}, retry {attempt + 1}/{MAX_RETRIES} in {wait:.0f}s", file=sys.stderr, flush=True)
            time.sleep(wait)


# ---------------------------------------------------------------------- backends
def call_gemini(llm, system, prompt, schema, seed):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    with llm._lock:
        if llm._client is None:
            llm._client = genai.Client()
    config = types.GenerateContentConfig(
        system_instruction=system or None,
        response_mime_type="application/json",
        response_schema=schema,
        max_output_tokens=llm.max_tokens,
        seed=int_seed(seed),
        thinking_config=types.ThinkingConfig(thinking_level=llm.thinking.upper()),
        automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
    )
    resp = with_retries(lambda: llm._client.models.generate_content(model=llm.model, contents=prompt, config=config),
                        genai.errors.APIError, "Gemini request")
    cand = resp.candidates[0] if resp.candidates else None
    reason = cand.finish_reason.name if cand and cand.finish_reason else None
    if reason == "MAX_TOKENS":
        raise LLMError(f"output truncated at max_tokens={llm.max_tokens}")
    if reason not in (None, "STOP"):
        raise LLMError(f"Gemini stopped with finish_reason={reason}")
    if resp.parsed is None:
        raise LLMError(f"no parsed output (finish_reason={reason}, feedback={resp.prompt_feedback})")
    if not resp.model_version:
        raise LLMError("Gemini response did not report which model answered")
    return resp.parsed.model_dump(), resp.model_version


def embed_gemini(llm, texts, batch=100):
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        raise LLMError("no Gemini credentials: set GEMINI_API_KEY")
    from google import genai
    from google.genai import types

    with llm._lock:
        if llm._client is None:
            llm._client = genai.Client()
    config = types.EmbedContentConfig(output_dimensionality=llm.dimensions) if llm.dimensions else None
    out = []
    for i in range(0, len(texts), batch):
        chunk = texts[i:i + batch]
        # one Content per text; a bare list of strings is embedded as a single item
        contents = [types.Content(parts=[types.Part(text=t)]) for t in chunk]
        resp = with_retries(lambda: llm._client.models.embed_content(model=llm.model, contents=contents, config=config),
                            genai.errors.APIError, "Gemini embedding")
        if len(resp.embeddings) != len(chunk):
            raise LLMError(f"asked for {len(chunk)} embeddings, got {len(resp.embeddings)}")
        out += [np.array(e.values, dtype=np.float32) for e in resp.embeddings]
    return out


def call_anthropic(llm, system, prompt, schema, seed):
    import anthropic

    with llm._lock:
        if llm._client is None:
            llm._client = anthropic.Anthropic()
    kwargs = dict(
        model=llm.model,
        max_tokens=llm.max_tokens,
        messages=[{"role": "user", "content": prompt}],
        output_format=schema,
        output_config={"effort": llm.thinking},
    )
    if system:
        kwargs["system"] = system
    if llm.provider_cfg.get("fallbacks"):
        kwargs.update(betas=[ANTHROPIC_FALLBACK_BETA], fallbacks=llm.provider_cfg["fallbacks"])
    try:
        resp = llm._client.beta.messages.parse(**kwargs)
    except anthropic.AuthenticationError as e:
        raise LLMError("no valid Anthropic credentials: set ANTHROPIC_API_KEY") from e
    except TypeError as e:          # SDK raises this when no credential resolves at all
        if "api_key" in str(e) or "auth" in str(e).lower():
            raise LLMError("no Anthropic credentials: set ANTHROPIC_API_KEY") from e
        raise
    if resp.stop_reason == "refusal":
        raise LLMError(f"model refused (request {resp._request_id}): {resp.stop_details}")
    if resp.stop_reason == "max_tokens":
        raise LLMError(f"output truncated at max_tokens={llm.max_tokens}")
    if resp.parsed_output is None:
        raise LLMError(f"no parsed output (stop_reason={resp.stop_reason})")
    return resp.parsed_output.model_dump(), resp.model


BACKENDS = {"gemini": call_gemini, "anthropic": call_anthropic}
EMBEDDERS = {"gemini": embed_gemini}
